### PR TITLE
Add global variable support

### PR DESCRIPTION
**Pull request by pardeike**
Because state rules!

### CODE REVIEW

**Comment by pardeike** [comment]
I use this with toggle switches and my Hue lamps to remember the last color before switching off. It's more reliable that way:

```js
// args = ['Licht Wohnzimmer,Licht Boden']
// ^ for testing

let names = _.split(args[0], ',')
let devices = await Homey.devices.getDevices();
let matches = _.filter(devices, d => _.includes(d.capabilities, 'dim') && _.includes(names, d.name));

var totalDim = 0;
_.forEach(matches, device => {
    let state = device.capabilitiesObj;
    let dim = state.dim.value;
    if (device.capabilitiesObj.onoff.value && dim == 0) dim = 0.5;
    if (dim > totalDim) totalDim = dim;
});

_.forEach(matches, device => {
    let state = device.capabilitiesObj;
    if (totalDim > 0) {
        let mode = save(device, 'light_mode');
        if (mode == 'color') {
            save(device, 'light_saturation');
            save(device, 'light_hue');
        } else
           save(device, 'light_temperature');
        device.setCapabilityValue('dim', 0);
    } else {
        let mode = load(device, 'light_mode');
        if (mode == 'color') {
            load(device, 'light_saturation');
            load(device, 'light_hue');
        } else
           load(device, 'light_temperature');
        device.setCapabilityValue('dim', 1);
    }
});

function save(device, key) {
    let val = device.capabilitiesObj[key].value;
    setGlobal(device.name + ' ' + key, val);
    log('Remember ' + device.name + ' ' + key + ' ' + val);
    return val;
}

function load(device, key) {
    if (_.includes(device.capabilities, key)) {
        let val = getGlobal(device.name + ' ' + key);
        device.setCapabilityValue(key, val);
        log('Restore ' + device.name + ' ' + key + ' ' + val);
        return val;
    }
    return null;
}
```

**Comment by psy0rz** [comment]
I would love this improvement. Now i use tags to keep state, like here: https://github.com/psy0rz/stuff/blob/master/homey/setonce.js

I think your system is cleaner and more efficient?

**Comment by pardeike** [comment]
I think it is. I might make it even more generic by introducing state that is separated by global/local. That is, have an extra namespace parameter that defaults to the current script but can be changed to something shared across scripts.

**Comment by jeroenvollenbrock** [comment]
Closed in favor of d72914a.

**Comment by pardeike** [comment]
Nice!

**Pull request closed without merging**
