### PR TITLE
add flow card examples

### PR DESCRIPTION
**Pull request by WeeJeWel**

### CODE REVIEW

**Review by jeroenwienk — APPROVED** [review]
Cool! day: 'weekend' reads a bit odd though :)

**Comment by WeeJeWel** [comment]
I know, what is a weekend anyway ☕️

**Comment by fiordache** [comment]
I receive an error : 
 TypeError: Homey.flow.runFlowCardAction is not a function

**Comment by jeroenwienk** [comment]
> I receive an error :
> TypeError: Homey.flow.runFlowCardAction is not a function

Could you give some more details and create and issue for this. [https://github.com/athombv/com.athom.homeyscript/issues](https://github.com/athombv/com.athom.homeyscript/issues)

- Homey version
- HomeyScript version
- How did you install it
- What script did you run (actual full code)

**Pull request merged**
